version: 0.2

env:
  variables:
    ENV_TEST_VAR: "A"

phases:
  install:
    runtime-versions:
      python: 3.7
    on-failure: ABORT       
    commands:
      - echo "Install Phase - $(which python3)"
  pre_build:
    on-failure: ABORT     
    commands:
      - echo terraform execution started on `date`            
  build:
    on-failure: ABORT   
    commands:
      - sh build.sh
  post_build:
    on-failure: CONTINUE   
    commands:
      - echo terraform execution completed on `date`      